### ISSUE TITLE
Get following issues on a clean installation with current README

### ISSUE THREAD

**Issue by junjuew** [cmusatyalab/gabriel#4]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/gabriel/server/bin/../gabriel/common/network/UPnP_server_binder.py", line 48, in run_exec
    self.proc = subprocess.Popen(cmd, close_fds = True, stdin = _PIPE, stdout = _PIPE, stderr = _PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by junjuew** [comment]
NVM. Forgot to install jre.
